<?php declare(strict_types=1);

namespace Zikan\Exception;

enum ContainerError: string
{
	case ALIAS_RECURSION = 'CONTAINER_ALIAS_RECURSION';
	case CALL_FAILURE = 'CONTAINER_CALL_FAILURE';
	case CLASS_NOT_FOUND = 'CONTAINER_CLASS_NOT_FOUND';
	case CREATE_FAILURE = 'CONTAINER_CREATE_FAILURE';
	case INSTANTIATE_FAILURE = 'CONTAINER_INSTANTIATE_FAILURE';
	case INVALID_ARGUMENT = 'CONTAINER_INVALID_ARGUMENT';
	case LOAD_FAILURE = 'CONTAINER_LOAD_FAILURE';
	case NOT_CALLABLE = 'CONTAINER_NOT_CALLABLE';
	case NOT_FOUND = 'CONTAINER_NOT_FOUND';
	case NOT_OBJECT = 'CONTAINER_NOT_OBJECT';
	case TYPE_FAILURE = 'CONTAINER_TYPE_FAILURE';
	case UNEXPECTED_CLASS = 'CONTAINER_UNEXPECTED_CLASS';
	case UNION_TYPE = 'CONTAINER_UNION_TYPE';
	case UNRESOLVED_PARAMETER = 'CONTAINER_UNRESOLVED_PARAMETER';
}
