<?php declare(strict_types=1);

namespace Zikan\Exception;

enum DispatchError: string
{
	case NO_ROUTE = 'DISPATCH_NO_ROUTE';
	case NO_CONTROLLER = 'DISPATCH_NO_CONTROLLER';
	case FAILED_ACTION = 'DISPATCH_FAILED_ACTION';
	case FAILED_INSTANTIATE = 'DISPATCH_FAILED_INSTANTIATE';
	case NO_ACTION = 'DISPATCH_NO_ACTION';
	case FAILED_INVOKE = 'DISPATCH_FAILED_INVOKE';
}
